2021-12-26 15:29:55.7608||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:23:42.4738||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:42.5063||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:42.5063||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:42.5179||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:49.0345||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:49.0345||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:49.0525||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:49.0525||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:23:56.3935||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:26:00.7611||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:26:00.7611||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:26:00.7780||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:26:00.7780||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:26:00.7847||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:34:50.7402||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:34:50.7623||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:34:50.7623||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:34:50.7711||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:34:54.1871||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:41:14.1312||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:41:14.1493||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:41:14.1493||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:41:14.1493||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:41:20.7819||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:51:48.4916||INFO|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Index sayfası başlamıştır. |url: https://localhost/Home2/Index|action: Index
2021-12-26 20:51:48.4916||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:51:48.5203||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:51:48.5203||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:51:48.5203||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:56:22.0602||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:56:22.0759||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:56:22.0797||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:56:22.0797||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 20:56:22.1426||ERROR|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Attempted to divide by zero. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29|url: https://localhost/Home2/Index|action: Index
2021-12-26 20:56:23.3160|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:06:02.6961||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:06:02.6961||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:06:02.7055||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:06:02.7055||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:06:10.0783||ERROR|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Attempted to divide by zero. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:06:11.4707|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:10:59.6438||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:10:59.6438||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:10:59.6603||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:10:59.6603||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:11:22.9552||ERROR|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Attempted to divide by zero. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:11:24.4388|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:17:59.4767||INFO|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:17:59.4874||WARN|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:17:59.4874||ERROR|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:17:59.4874||FATAL|NetCoreLibraries.Logging.Web.Controllers.HomeController|Index sayfasına girildi |url: https://localhost/|action: Index
2021-12-26 21:18:05.9534||ERROR|NetCoreLibraries.Logging.Web.Controllers.Home2Controller|Attempted to divide by zero. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29|url: https://localhost/Home2/Index|action: Index
2021-12-26 21:18:06.9089|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.DivideByZeroException: Attempted to divide by zero.
   at NetCoreLibraries.Logging.Web.Controllers.Home2Controller.Index() in C:\Users\aktur\Desktop\NetCoreLibraries\NetCoreLibraries\NetCoreLibraries.Logging.Web\Controllers\Home2Controller.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: https://localhost/Home2/Index|action: Index
